version: '3.8'

services:
  # Required Infrastructure
  eureka-server:
    image: myprof/eureka-server:latest
    ports:
      - "8761:8761"

  config-server:
    image: myprof/config-server:latest
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  api-gateway:
    image: myprof/api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server

  # Databases
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: myprof_auth,myprof_profile,myprof_authorization
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
