version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: myprof_auth,myprof_profile,myprof_authorization
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myprof_auth
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  profile-service:
    build: ./profile-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myprof_profile
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  authorization-service:
    build: ./authorization-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myprof_authorization
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8084:8084"
    depends_on:
      - auth-service
      - profile-service
      - authorization-service

volumes:
  postgres_data:
