name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Auth Service
      uses: docker/build-push-action@v4
      with:
        context: ./auth-service
        push: true
        tags: |
          ${{ env.REGISTRY }}/myprof/auth-service:latest
          ${{ env.REGISTRY }}/myprof/auth-service:${{ env.IMAGE_TAG }}

    - name: Build and Push Profile Service
      uses: docker/build-push-action@v4
      with:
        context: ./profile-service
        push: true
        tags: |
          ${{ env.REGISTRY }}/myprof/profile-service:latest
          ${{ env.REGISTRY }}/myprof/profile-service:${{ env.IMAGE_TAG }}

    - name: Build and Push Authorization Service
      uses: docker/build-push-action@v4
      with:
        context: ./authorization-service
        push: true
        tags: |
          ${{ env.REGISTRY }}/myprof/authorization-service:latest
          ${{ env.REGISTRY }}/myprof/authorization-service:${{ env.IMAGE_TAG }}

    - name: Build and Push User Service
      uses: docker/build-push-action@v4
      with:
        context: ./user-service
        push: true
        tags: |
          ${{ env.REGISTRY }}/myprof/user-service:latest
          ${{ env.REGISTRY }}/myprof/user-service:${{ env.IMAGE_TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Update Kubernetes Deployments
      run: |
        kubectl apply -f k8s/auth-service.yaml
        kubectl apply -f k8s/profile-service.yaml
        kubectl apply -f k8s/authorization-service.yaml
        kubectl apply -f k8s/user-service.yaml

    - name: Verify Deployments
      run: |
        kubectl rollout status deployment/auth-service
        kubectl rollout status deployment/profile-service
        kubectl rollout status deployment/authorization-service
        kubectl rollout status deployment/user-service
