name: Coverage Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  java-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, profile-service, authorization-service, user-service]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Calculate Coverage
        run: |
          cd ${{ matrix.service }}
          mvn clean verify jacoco:report

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./${{ matrix.service }}/target/site/jacoco/jacoco.xml
          flags: ${{ matrix.service }}
          name: ${{ matrix.service }}-coverage
          fail_ci_if_error: true

      - name: Check Coverage Thresholds
        run: |
          cd ${{ matrix.service }}
          mvn jacoco:check \
            -Djacoco.minimum.line.coverage=0.80 \
            -Djacoco.minimum.branch.coverage=0.70 \
            -Djacoco.minimum.complexity.coverage=0.70

      - name: Generate Coverage Report
        run: |
          cd ${{ matrix.service }}
          mvn site -DgenerateReports=false
          mvn jacoco:report-aggregate

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.service }}
          path: |
            ${{ matrix.service }}/target/site/jacoco
            ${{ matrix.service }}/target/site/jacoco-aggregate
