name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  java-integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_MULTIPLE_DATABASES: myprof_auth,myprof_profile,myprof_authorization
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        service: [auth-service, profile-service, authorization-service, user-service]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Integration Tests for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn verify -P integration-test -Dspring.profiles.active=test

      - name: Generate Integration Test Report
        if: always()
        run: |
          cd ${{ matrix.service }}
          mvn failsafe:report

      - name: Upload Integration Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results-${{ matrix.service }}
          path: |
            ${{ matrix.service }}/target/failsafe-reports
            ${{ matrix.service }}/target/site
